name: waflo_admin
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

#------------------PACKAGES-------------------
dependencies:
  flutter:
    sdk: flutter


  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # Utility Packages
  http: ^0.13.5
  intl: ^0.18.1
  logger: ^1.4.0
  url_launcher: ^6.1.8
  flutter_native_splash: ^2.1.6
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  tiengviet: ^1.0.0
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


#------------------LOCAL STORAGE-------------------
  assets:
    
    - assets/images/
    - assets/icons/
    - assets/logos/
    - google_fonts/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/products/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/reviews/